# If you want to use any example, just remove the comment character (#).

[table]
# Here specify in what sheet is this table located, and the individual headers.

# To specify the sheet:
sheet = "Sheet1"

# To specify the headers, example:
#row_header.name = "A"
#column_header.year = 1
#column_header.month = 2
# or in transposed table:
#row_header.year = "A"
#row_header.month = "B"
#column_header.name = 1

[filter]
# Here you can specify the filters that get applied to the table for each graph. These may be overriden in each graph.

# Filtering is done on each header, by specifying the values to include

# If there are multiple headers of the same direction (e.g. "row_header.year" and "row_header.month"), you can specify the filters for each header:
#row.year = ["2020", "2021"]
#row.month = ["January", "February"]
# The same applies for column headers:
#column.value = ["Value1", "Value2"]
